### ISSUE TITLE
EME Requires MSE

### ISSUE THREAD

**Issue by btsimonh** [cpearce/eme-in-non-fragmented-mp4#1]
Hi, just a note here that it's not necessarily fragmentation, but rather MSE.
You CAN push a single file fMP4 into MSE and EME works.  But without MSE, Firefox tells you it won't do it, and Chrome just silently ignores you (no onencrypted message).

**Comment by cpearce** [comment]
Correct. I implemented EME in Firefox, and at the time we didn't see any demand for EME outside of MSE. So while it works in Firefox if you pref it on in about:config (our internal architecture made it trivially easy to implement), we never shipped it and never supported it officially. This repo was created to test the initial easy implementation that we never shipped.
